# Generated by Django 5.2.15 on 2026-07-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_headquarters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Headquarters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubHeadquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_headquarters', to=settings.AUTH_USER_MODEL)),
                ('headquarters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_headquarters', to='organizations.headquarters')),
            ],
            options={
                'verbose_name_plural': 'Sub Headquarters',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('headquarters', 'code'), name='unique_sub_hq_code_per_hq')],
            },
        ),
    ]
