# Generated by Django 5.2.15 on 2026-07-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mr', models.ForeignKey(blank=True, limit_choices_to={'role': 'MR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doctors', to=settings.AUTH_USER_MODEL)),
                ('headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='organizations.headquarters')),
                ('sub_headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='organizations.subheadquarters')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['headquarters'], name='doctors_doc_headqua_966cf0_idx'), models.Index(fields=['sub_headquarters'], name='doctors_doc_sub_hea_54a995_idx'), models.Index(fields=['assigned_mr'], name='doctors_doc_assigne_bab128_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('headquarters__isnull', False), ('sub_headquarters__isnull', True)), models.Q(('headquarters__isnull', True), ('sub_headquarters__isnull', False)), _connector='OR'), name='doctor_exactly_one_parent')],
            },
        ),
    ]
